# Site settings
title: 18F Guides
description: > # this means to ignore newlines until "baseurl:"
  Welcome to 18F Guides!
baseurl: "/guides"
url: "https://pages.18f.gov"

# Header
header:
  logo_text: 18F Guides
  logo_img: logo.svg
  # nav:
  #   - text: Article
  #     link: /example-article
  #   - text: About
  #     link: /about
  #   - text: Blog
  #     link: /blog

# Edit pages
edit_page:
  # enabled: true  # Enabled by default for pages and posts
  text: "Improve this content »"
  github:
    author: 18F
    repo:   guides
    branch: gh-pages

# Posts
posts_path: /blog
permalink: "/blog/:year/:month/:day/:title"

# Pagination
paginate: 5
paginate_path: "/blog/page:num"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [hard_wrap, tables]

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: template/page
  - scope:
      path: ""
      type: posts
    values:
      layout: template/post
