markdown: redcarpet
name: 18F Guides
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

author:
  name: 18F
  url: https://18f.gsa.gov

navigation:
- text: Accessibility
  url: https://accessibility.18f.gov
- text: Agile
  url: https://agile.18f.gov
- text: Content Guide
  url: https://content-guide.18f.gov
- text: Design Methods
  url: https://methods.18f.gov
- text: Design Principles Guide
  url: https://design-principles-guide.18f.gov
- text: Front End
  url: https://frontend.18f.gov
- text: Product
  url: https://product-guide.18f.gov

google_analytics_ua: UA-48605964-19

repos:
- name: 18F Guides
  description: 18F Guides GitHub repository
  url: https://github.com/18F/guides

back_link:
  url: "https://18f.gsa.gov/"
  text: Back to 18F Homepage

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
